// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyContacts.DataAccessLayer.DAL;

#nullable disable

namespace MyContacts.DataAccessLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MyContacts.DataAccessLayer.ContactInformation.ContactDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<int?>("LabelId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LabelId");

                    b.ToTable("ContactDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "6th",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(5237),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Beryl",
                            Image = "http://dummyimage.com/228x100.png/5fa2dd/ffffff",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 4,
                            LastName = "Krug",
                            Notes = "Stanley Black & Decker, Inc."
                        },
                        new
                        {
                            Id = 2,
                            Address = "Messerschmidt",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(5516),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Nerissa",
                            Image = "http://dummyimage.com/105x100.png/ff4444/ffffff",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 1,
                            LastName = "Cammocke",
                            Notes = "PPlus Trust"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Coleman",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(5605),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Saloma",
                            Image = "http://dummyimage.com/144x100.png/5fa2dd/ffffff",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 5,
                            LastName = "Partington",
                            Notes = "Fuwei Films (Holdings) Co., Ltd."
                        },
                        new
                        {
                            Id = 4,
                            Address = "Beilfuss",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(5687),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Coreen",
                            Image = "http://dummyimage.com/102x100.png/dddddd/000000",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 2,
                            LastName = "Domelow",
                            Notes = "Allegheny Technologies Incorporated"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Tony",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(5767),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Brook",
                            Image = "http://dummyimage.com/123x100.png/ff4444/ffffff",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 5,
                            LastName = "Tommaseo",
                            Notes = "Core Laboratories N.V."
                        },
                        new
                        {
                            Id = 6,
                            Address = "Shelley",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(5851),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Brunhilda",
                            Image = "http://dummyimage.com/176x100.png/dddddd/000000",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 3,
                            LastName = "Flanner",
                            Notes = "Francesca's Holdings Corporation"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Esch",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(5948),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Channa",
                            Image = "http://dummyimage.com/100x100.png/ff4444/ffffff",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 1,
                            LastName = "De Vere",
                            Notes = "Ingersoll-Rand plc (Ireland)"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Loomis",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(6028),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Carolann",
                            Image = "http://dummyimage.com/161x100.png/dddddd/000000",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 2,
                            LastName = "Hamblin",
                            Notes = "PowerShares DWA Emerging Markets Momentum Portfolio"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Truax",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(6108),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Darbie",
                            Image = "http://dummyimage.com/240x100.png/cc0000/ffffff",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 5,
                            LastName = "Charon",
                            Notes = "ZAGG Inc"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Dovetail",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(6190),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Shellie",
                            Image = "http://dummyimage.com/141x100.png/5fa2dd/ffffff",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 1,
                            LastName = "Keightley",
                            Notes = "American Public Education, Inc."
                        },
                        new
                        {
                            Id = 11,
                            Address = "La Follette",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(6306),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Tomasine",
                            Image = "http://dummyimage.com/222x100.png/dddddd/000000",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 1,
                            LastName = "Baly",
                            Notes = "Treehouse Foods, Inc."
                        },
                        new
                        {
                            Id = 12,
                            Address = "Eliot",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(6392),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Barton",
                            Image = "http://dummyimage.com/112x100.png/ff4444/ffffff",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 2,
                            LastName = "Boorer",
                            Notes = "RealPage, Inc."
                        },
                        new
                        {
                            Id = 13,
                            Address = "Steensland",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(6472),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Amata",
                            Image = "http://dummyimage.com/178x100.png/ff4444/ffffff",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 4,
                            LastName = "Middle",
                            Notes = "Capital One Financial Corporation"
                        },
                        new
                        {
                            Id = 14,
                            Address = "Gina",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(6551),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Eal",
                            Image = "http://dummyimage.com/210x100.png/cc0000/ffffff",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 2,
                            LastName = "Yurocjhin",
                            Notes = "PAVmed Inc."
                        },
                        new
                        {
                            Id = 15,
                            Address = "Barnett",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(6631),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Hildagard",
                            Image = "http://dummyimage.com/171x100.png/cc0000/ffffff",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 5,
                            LastName = "Aimeric",
                            Notes = "Great Elm Capital Corp."
                        },
                        new
                        {
                            Id = 16,
                            Address = "Mitchell",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(6711),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Liva",
                            Image = "http://dummyimage.com/178x100.png/5fa2dd/ffffff",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 2,
                            LastName = "Birds",
                            Notes = "Galena Biopharma, Inc."
                        },
                        new
                        {
                            Id = 17,
                            Address = "Grayhawk",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(6791),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Wash",
                            Image = "http://dummyimage.com/248x100.png/5fa2dd/ffffff",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 1,
                            LastName = "Crowthe",
                            Notes = "DoubleLine Income Solutions Fund"
                        },
                        new
                        {
                            Id = 18,
                            Address = "Kropf",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(6876),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ursala",
                            Image = "http://dummyimage.com/210x100.png/ff4444/ffffff",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 4,
                            LastName = "Ousley",
                            Notes = "Nova Measuring Instruments Ltd."
                        },
                        new
                        {
                            Id = 19,
                            Address = "Mesta",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(6956),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Codi",
                            Image = "http://dummyimage.com/168x100.png/ff4444/ffffff",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 1,
                            LastName = "Kensy",
                            Notes = "REV Group, Inc."
                        },
                        new
                        {
                            Id = 20,
                            Address = "3rd",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(7035),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Daisi",
                            Image = "http://dummyimage.com/161x100.png/dddddd/000000",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 2,
                            LastName = "Hegarty",
                            Notes = "Old Second Bancorp, Inc."
                        },
                        new
                        {
                            Id = 21,
                            Address = "Crest Line",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(7115),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Menard",
                            Image = "http://dummyimage.com/139x100.png/cc0000/ffffff",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 5,
                            LastName = "Katte",
                            Notes = "Primo Water Corporation"
                        },
                        new
                        {
                            Id = 22,
                            Address = "Arizona",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(7197),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jermaine",
                            Image = "http://dummyimage.com/200x100.png/ff4444/ffffff",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 4,
                            LastName = "Tithacott",
                            Notes = "Vantage Energy Acquisition Corp."
                        },
                        new
                        {
                            Id = 23,
                            Address = "Aberg",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(7279),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Leelah",
                            Image = "http://dummyimage.com/180x100.png/dddddd/000000",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 2,
                            LastName = "Saing",
                            Notes = "ARC Group Worldwide, Inc."
                        },
                        new
                        {
                            Id = 24,
                            Address = "Grover",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(7359),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Durante",
                            Image = "http://dummyimage.com/125x100.png/5fa2dd/ffffff",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 2,
                            LastName = "Huddleston",
                            Notes = "Saban Capital Acquisition Corp."
                        },
                        new
                        {
                            Id = 25,
                            Address = "Sachs",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(7439),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Rudy",
                            Image = "http://dummyimage.com/210x100.png/5fa2dd/ffffff",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 1,
                            LastName = "Wardle",
                            Notes = "Landstar System, Inc."
                        },
                        new
                        {
                            Id = 26,
                            Address = "Lindbergh",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(7519),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Marion",
                            Image = "http://dummyimage.com/205x100.png/ff4444/ffffff",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 4,
                            LastName = "Dilnot",
                            Notes = "Aegion Corp"
                        },
                        new
                        {
                            Id = 27,
                            Address = "Homewood",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(7598),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Effie",
                            Image = "http://dummyimage.com/246x100.png/dddddd/000000",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 2,
                            LastName = "Eddow",
                            Notes = "Nuveen Maryland Quality Municipal Income Fund"
                        },
                        new
                        {
                            Id = 28,
                            Address = "Lillian",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(7724),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kinsley",
                            Image = "http://dummyimage.com/210x100.png/dddddd/000000",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 4,
                            LastName = "Rolph",
                            Notes = "Ion Geophysical Corporation"
                        },
                        new
                        {
                            Id = 29,
                            Address = "Blaine",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(7803),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Martie",
                            Image = "http://dummyimage.com/216x100.png/dddddd/000000",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 5,
                            LastName = "Keave",
                            Notes = "Danaos Corporation"
                        },
                        new
                        {
                            Id = 30,
                            Address = "Doe Crossing",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(7882),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Hamilton",
                            Image = "http://dummyimage.com/207x100.png/cc0000/ffffff",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 4,
                            LastName = "Penney",
                            Notes = "QIWI plc"
                        },
                        new
                        {
                            Id = 31,
                            Address = "Schiller",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(7961),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Niles",
                            Image = "http://dummyimage.com/181x100.png/5fa2dd/ffffff",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 4,
                            LastName = "Bottrill",
                            Notes = "Arbor Realty Trust"
                        },
                        new
                        {
                            Id = 32,
                            Address = "Kings",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(8040),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sallie",
                            Image = "http://dummyimage.com/209x100.png/cc0000/ffffff",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 3,
                            LastName = "Firbanks",
                            Notes = "Nuveen Preferred Income Opportunites Fund"
                        },
                        new
                        {
                            Id = 33,
                            Address = "Lyons",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(8122),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Felice",
                            Image = "http://dummyimage.com/247x100.png/ff4444/ffffff",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 2,
                            LastName = "Goddard",
                            Notes = "Walgreens Boots Alliance, Inc."
                        },
                        new
                        {
                            Id = 34,
                            Address = "Grim",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(8205),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Gale",
                            Image = "http://dummyimage.com/209x100.png/ff4444/ffffff",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 2,
                            LastName = "Cholwell",
                            Notes = "Coach, Inc."
                        },
                        new
                        {
                            Id = 35,
                            Address = "Vermont",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(8284),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Teresina",
                            Image = "http://dummyimage.com/155x100.png/5fa2dd/ffffff",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 1,
                            LastName = "Arnold",
                            Notes = "Vertex Pharmaceuticals Incorporated"
                        },
                        new
                        {
                            Id = 36,
                            Address = "Cardinal",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(8363),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Shayne",
                            Image = "http://dummyimage.com/120x100.png/cc0000/ffffff",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 3,
                            LastName = "Bankhurst",
                            Notes = "BLACKROCK INTERNATIONAL, LTD."
                        },
                        new
                        {
                            Id = 37,
                            Address = "Thierer",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(8443),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Emlyn",
                            Image = "http://dummyimage.com/235x100.png/cc0000/ffffff",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 3,
                            LastName = "Gheorghescu",
                            Notes = "eHealth, Inc."
                        },
                        new
                        {
                            Id = 38,
                            Address = "Basil",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(8526),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ricoriki",
                            Image = "http://dummyimage.com/237x100.png/5fa2dd/ffffff",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 2,
                            LastName = "Olivetta",
                            Notes = "Moody's Corporation"
                        },
                        new
                        {
                            Id = 39,
                            Address = "Muir",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(8606),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Lowrance",
                            Image = "http://dummyimage.com/161x100.png/dddddd/000000",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 5,
                            LastName = "Steart",
                            Notes = "Lifetime Brands, Inc."
                        },
                        new
                        {
                            Id = 40,
                            Address = "Arkansas",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(8685),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jens",
                            Image = "http://dummyimage.com/164x100.png/5fa2dd/ffffff",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 5,
                            LastName = "Purcell",
                            Notes = "Advanced Micro Devices, Inc."
                        },
                        new
                        {
                            Id = 41,
                            Address = "Charing Cross",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(8764),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Wash",
                            Image = "http://dummyimage.com/124x100.png/dddddd/000000",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 5,
                            LastName = "Setterington",
                            Notes = "Workhorse Group, Inc."
                        },
                        new
                        {
                            Id = 42,
                            Address = "Hovde",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(8844),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Andris",
                            Image = "http://dummyimage.com/104x100.png/5fa2dd/ffffff",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 2,
                            LastName = "Benford",
                            Notes = "Nuveen Missouri Quality Municipal Income Fund"
                        },
                        new
                        {
                            Id = 43,
                            Address = "Delaware",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(8958),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Colman",
                            Image = "http://dummyimage.com/173x100.png/dddddd/000000",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 4,
                            LastName = "Jaggli",
                            Notes = "iRobot Corporation"
                        },
                        new
                        {
                            Id = 44,
                            Address = "Buena Vista",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(9041),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Elka",
                            Image = "http://dummyimage.com/119x100.png/5fa2dd/ffffff",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 2,
                            LastName = "Fontel",
                            Notes = "Easterly Acquisition Corp."
                        },
                        new
                        {
                            Id = 45,
                            Address = "North",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(9121),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Hyacinthia",
                            Image = "http://dummyimage.com/156x100.png/5fa2dd/ffffff",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 1,
                            LastName = "Dine-Hart",
                            Notes = "Cray Inc"
                        },
                        new
                        {
                            Id = 46,
                            Address = "Susan",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(9201),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Reynold",
                            Image = "http://dummyimage.com/214x100.png/ff4444/ffffff",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 3,
                            LastName = "Simonson",
                            Notes = "iShares MSCI New Zealand Capped ETF"
                        },
                        new
                        {
                            Id = 47,
                            Address = "Morning",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(9281),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Lorene",
                            Image = "http://dummyimage.com/107x100.png/cc0000/ffffff",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 5,
                            LastName = "Almeida",
                            Notes = "China TechFaith Wireless Communication Technology Limited"
                        },
                        new
                        {
                            Id = 48,
                            Address = "Troy",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(9363),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Hubie",
                            Image = "http://dummyimage.com/142x100.png/ff4444/ffffff",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 1,
                            LastName = "Lapthorn",
                            Notes = "Vornado Realty Trust"
                        },
                        new
                        {
                            Id = 49,
                            Address = "American Ash",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(9446),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Thor",
                            Image = "http://dummyimage.com/249x100.png/5fa2dd/ffffff",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 5,
                            LastName = "Muzzini",
                            Notes = "Southwest Bancorp, Inc."
                        },
                        new
                        {
                            Id = 50,
                            Address = "Coolidge",
                            DateCreated = new DateTime(2022, 4, 7, 16, 7, 1, 174, DateTimeKind.Local).AddTicks(9526),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Artair",
                            Image = "http://dummyimage.com/205x100.png/5fa2dd/ffffff",
                            IsDeleted = false,
                            IsPublished = true,
                            LabelId = 1,
                            LastName = "Rowsell",
                            Notes = "Champions Oncology, Inc."
                        });
                });

            modelBuilder.Entity("MyContacts.DataAccessLayer.ContactInformation.Label", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Labels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Site Furnishings"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Elevator"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Roofing (Asphalt)"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Drilled Shafts"
                        },
                        new
                        {
                            Id = 5,
                            Title = "Site Furnishings"
                        });
                });

            modelBuilder.Entity("MyContacts.DataAccessLayer.ContactInformation.PhoneNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ContactDetailId")
                        .HasColumnType("int");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContactDetailId");

                    b.ToTable("PhoneNumbers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactDetailId = 15,
                            ContactNumber = "627-665-0678",
                            Title = "Hummer"
                        },
                        new
                        {
                            Id = 2,
                            ContactDetailId = 17,
                            ContactNumber = "453-900-2333",
                            Title = "Chevrolet"
                        },
                        new
                        {
                            Id = 3,
                            ContactDetailId = 9,
                            ContactNumber = "675-324-9212",
                            Title = "BMW"
                        },
                        new
                        {
                            Id = 4,
                            ContactDetailId = 1,
                            ContactNumber = "834-902-4183",
                            Title = "Chevrolet"
                        },
                        new
                        {
                            Id = 5,
                            ContactDetailId = 1,
                            ContactNumber = "963-206-2352",
                            Title = "Dodge"
                        },
                        new
                        {
                            Id = 6,
                            ContactDetailId = 35,
                            ContactNumber = "231-566-7124",
                            Title = "Hyundai"
                        },
                        new
                        {
                            Id = 7,
                            ContactDetailId = 3,
                            ContactNumber = "573-657-8555",
                            Title = "Mercury"
                        },
                        new
                        {
                            Id = 8,
                            ContactDetailId = 21,
                            ContactNumber = "546-950-5986",
                            Title = "GMC"
                        },
                        new
                        {
                            Id = 9,
                            ContactDetailId = 40,
                            ContactNumber = "618-452-5965",
                            Title = "Morgan"
                        },
                        new
                        {
                            Id = 10,
                            ContactDetailId = 28,
                            ContactNumber = "723-253-6389",
                            Title = "Buick"
                        },
                        new
                        {
                            Id = 11,
                            ContactDetailId = 14,
                            ContactNumber = "306-362-5238",
                            Title = "Toyota"
                        },
                        new
                        {
                            Id = 12,
                            ContactDetailId = 6,
                            ContactNumber = "274-641-5926",
                            Title = "Holden"
                        },
                        new
                        {
                            Id = 13,
                            ContactDetailId = 11,
                            ContactNumber = "307-482-6522",
                            Title = "GMC"
                        },
                        new
                        {
                            Id = 14,
                            ContactDetailId = 39,
                            ContactNumber = "404-203-3548",
                            Title = "Tesla"
                        },
                        new
                        {
                            Id = 15,
                            ContactDetailId = 7,
                            ContactNumber = "225-249-6710",
                            Title = "Volkswagen"
                        },
                        new
                        {
                            Id = 16,
                            ContactDetailId = 33,
                            ContactNumber = "646-996-7798",
                            Title = "Chevrolet"
                        },
                        new
                        {
                            Id = 17,
                            ContactDetailId = 30,
                            ContactNumber = "226-168-9195",
                            Title = "Chevrolet"
                        },
                        new
                        {
                            Id = 18,
                            ContactDetailId = 18,
                            ContactNumber = "133-792-3686",
                            Title = "GMC"
                        },
                        new
                        {
                            Id = 19,
                            ContactDetailId = 26,
                            ContactNumber = "416-141-7934",
                            Title = "Saab"
                        },
                        new
                        {
                            Id = 20,
                            ContactDetailId = 48,
                            ContactNumber = "835-851-6003",
                            Title = "Mitsubishi"
                        },
                        new
                        {
                            Id = 21,
                            ContactDetailId = 28,
                            ContactNumber = "398-893-8147",
                            Title = "Nissan"
                        },
                        new
                        {
                            Id = 22,
                            ContactDetailId = 9,
                            ContactNumber = "369-990-3510",
                            Title = "Nissan"
                        },
                        new
                        {
                            Id = 23,
                            ContactDetailId = 25,
                            ContactNumber = "326-298-1347",
                            Title = "Isuzu"
                        },
                        new
                        {
                            Id = 24,
                            ContactDetailId = 8,
                            ContactNumber = "517-438-2579",
                            Title = "Toyota"
                        },
                        new
                        {
                            Id = 25,
                            ContactDetailId = 15,
                            ContactNumber = "172-926-5800",
                            Title = "Volkswagen"
                        },
                        new
                        {
                            Id = 26,
                            ContactDetailId = 5,
                            ContactNumber = "565-552-2967",
                            Title = "GMC"
                        },
                        new
                        {
                            Id = 27,
                            ContactDetailId = 3,
                            ContactNumber = "436-684-3121",
                            Title = "Mercury"
                        },
                        new
                        {
                            Id = 28,
                            ContactDetailId = 8,
                            ContactNumber = "376-557-2386",
                            Title = "Ford"
                        },
                        new
                        {
                            Id = 29,
                            ContactDetailId = 10,
                            ContactNumber = "970-307-3888",
                            Title = "Volkswagen"
                        },
                        new
                        {
                            Id = 30,
                            ContactDetailId = 9,
                            ContactNumber = "430-452-8703",
                            Title = "BMW"
                        },
                        new
                        {
                            Id = 31,
                            ContactDetailId = 22,
                            ContactNumber = "727-311-0828",
                            Title = "Saturn"
                        },
                        new
                        {
                            Id = 32,
                            ContactDetailId = 34,
                            ContactNumber = "757-245-9053",
                            Title = "Mitsubishi"
                        },
                        new
                        {
                            Id = 33,
                            ContactDetailId = 20,
                            ContactNumber = "291-414-7260",
                            Title = "BMW"
                        },
                        new
                        {
                            Id = 34,
                            ContactDetailId = 7,
                            ContactNumber = "155-324-8356",
                            Title = "Mercedes-Benz"
                        },
                        new
                        {
                            Id = 35,
                            ContactDetailId = 45,
                            ContactNumber = "642-856-8367",
                            Title = "Ford"
                        },
                        new
                        {
                            Id = 36,
                            ContactDetailId = 28,
                            ContactNumber = "350-909-2389",
                            Title = "Mitsubishi"
                        },
                        new
                        {
                            Id = 37,
                            ContactDetailId = 13,
                            ContactNumber = "423-101-8028",
                            Title = "Chevrolet"
                        },
                        new
                        {
                            Id = 38,
                            ContactDetailId = 44,
                            ContactNumber = "687-530-1672",
                            Title = "Chevrolet"
                        },
                        new
                        {
                            Id = 39,
                            ContactDetailId = 3,
                            ContactNumber = "636-329-1306",
                            Title = "Pontiac"
                        },
                        new
                        {
                            Id = 40,
                            ContactDetailId = 4,
                            ContactNumber = "315-693-5581",
                            Title = "Mazda"
                        },
                        new
                        {
                            Id = 41,
                            ContactDetailId = 47,
                            ContactNumber = "793-993-8568",
                            Title = "Ford"
                        },
                        new
                        {
                            Id = 42,
                            ContactDetailId = 48,
                            ContactNumber = "224-387-5371",
                            Title = "Saturn"
                        },
                        new
                        {
                            Id = 43,
                            ContactDetailId = 46,
                            ContactNumber = "769-133-2247",
                            Title = "Mercedes-Benz"
                        },
                        new
                        {
                            Id = 44,
                            ContactDetailId = 37,
                            ContactNumber = "996-455-1897",
                            Title = "Aston Martin"
                        },
                        new
                        {
                            Id = 45,
                            ContactDetailId = 10,
                            ContactNumber = "624-205-2657",
                            Title = "GMC"
                        },
                        new
                        {
                            Id = 46,
                            ContactDetailId = 41,
                            ContactNumber = "226-226-9425",
                            Title = "Jaguar"
                        },
                        new
                        {
                            Id = 47,
                            ContactDetailId = 22,
                            ContactNumber = "415-314-2321",
                            Title = "Mitsubishi"
                        },
                        new
                        {
                            Id = 48,
                            ContactDetailId = 14,
                            ContactNumber = "628-570-4878",
                            Title = "Lexus"
                        },
                        new
                        {
                            Id = 49,
                            ContactDetailId = 13,
                            ContactNumber = "999-860-5185",
                            Title = "Mercedes-Benz"
                        },
                        new
                        {
                            Id = 50,
                            ContactDetailId = 12,
                            ContactNumber = "904-246-6413",
                            Title = "MINI"
                        },
                        new
                        {
                            Id = 51,
                            ContactDetailId = 41,
                            ContactNumber = "201-566-1980",
                            Title = "Mercedes-Benz"
                        },
                        new
                        {
                            Id = 52,
                            ContactDetailId = 41,
                            ContactNumber = "599-253-6458",
                            Title = "Pontiac"
                        },
                        new
                        {
                            Id = 53,
                            ContactDetailId = 41,
                            ContactNumber = "967-306-0532",
                            Title = "Pontiac"
                        },
                        new
                        {
                            Id = 54,
                            ContactDetailId = 3,
                            ContactNumber = "970-556-8902",
                            Title = "Lamborghini"
                        },
                        new
                        {
                            Id = 55,
                            ContactDetailId = 33,
                            ContactNumber = "663-354-5146",
                            Title = "Audi"
                        },
                        new
                        {
                            Id = 56,
                            ContactDetailId = 3,
                            ContactNumber = "880-643-5283",
                            Title = "Land Rover"
                        },
                        new
                        {
                            Id = 57,
                            ContactDetailId = 11,
                            ContactNumber = "170-917-8444",
                            Title = "Oldsmobile"
                        },
                        new
                        {
                            Id = 58,
                            ContactDetailId = 2,
                            ContactNumber = "251-630-2392",
                            Title = "Audi"
                        },
                        new
                        {
                            Id = 59,
                            ContactDetailId = 50,
                            ContactNumber = "777-252-9683",
                            Title = "Chevrolet"
                        },
                        new
                        {
                            Id = 60,
                            ContactDetailId = 3,
                            ContactNumber = "284-320-4015",
                            Title = "GMC"
                        },
                        new
                        {
                            Id = 61,
                            ContactDetailId = 32,
                            ContactNumber = "699-524-2695",
                            Title = "Jaguar"
                        },
                        new
                        {
                            Id = 62,
                            ContactDetailId = 24,
                            ContactNumber = "760-707-2719",
                            Title = "Subaru"
                        },
                        new
                        {
                            Id = 63,
                            ContactDetailId = 32,
                            ContactNumber = "334-242-6040",
                            Title = "Subaru"
                        },
                        new
                        {
                            Id = 64,
                            ContactDetailId = 30,
                            ContactNumber = "328-950-1599",
                            Title = "Suzuki"
                        },
                        new
                        {
                            Id = 65,
                            ContactDetailId = 12,
                            ContactNumber = "553-289-8678",
                            Title = "GMC"
                        },
                        new
                        {
                            Id = 66,
                            ContactDetailId = 12,
                            ContactNumber = "473-707-8438",
                            Title = "BMW"
                        },
                        new
                        {
                            Id = 67,
                            ContactDetailId = 36,
                            ContactNumber = "271-416-3302",
                            Title = "GMC"
                        },
                        new
                        {
                            Id = 68,
                            ContactDetailId = 31,
                            ContactNumber = "904-965-7567",
                            Title = "GMC"
                        },
                        new
                        {
                            Id = 69,
                            ContactDetailId = 50,
                            ContactNumber = "869-671-4096",
                            Title = "Saturn"
                        },
                        new
                        {
                            Id = 70,
                            ContactDetailId = 46,
                            ContactNumber = "235-894-9238",
                            Title = "Acura"
                        },
                        new
                        {
                            Id = 71,
                            ContactDetailId = 36,
                            ContactNumber = "142-240-7198",
                            Title = "Maybach"
                        },
                        new
                        {
                            Id = 72,
                            ContactDetailId = 25,
                            ContactNumber = "485-947-0473",
                            Title = "Toyota"
                        },
                        new
                        {
                            Id = 73,
                            ContactDetailId = 50,
                            ContactNumber = "550-208-6192",
                            Title = "Honda"
                        },
                        new
                        {
                            Id = 74,
                            ContactDetailId = 23,
                            ContactNumber = "495-884-4643",
                            Title = "Plymouth"
                        },
                        new
                        {
                            Id = 75,
                            ContactDetailId = 30,
                            ContactNumber = "822-174-3464",
                            Title = "Toyota"
                        },
                        new
                        {
                            Id = 76,
                            ContactDetailId = 3,
                            ContactNumber = "799-334-7709",
                            Title = "Lincoln"
                        },
                        new
                        {
                            Id = 77,
                            ContactDetailId = 3,
                            ContactNumber = "804-991-4613",
                            Title = "BMW"
                        },
                        new
                        {
                            Id = 78,
                            ContactDetailId = 9,
                            ContactNumber = "639-745-1091",
                            Title = "Lamborghini"
                        },
                        new
                        {
                            Id = 79,
                            ContactDetailId = 49,
                            ContactNumber = "358-356-5098",
                            Title = "Maybach"
                        },
                        new
                        {
                            Id = 80,
                            ContactDetailId = 25,
                            ContactNumber = "572-886-2023",
                            Title = "Toyota"
                        },
                        new
                        {
                            Id = 81,
                            ContactDetailId = 15,
                            ContactNumber = "280-567-9893",
                            Title = "Mazda"
                        },
                        new
                        {
                            Id = 82,
                            ContactDetailId = 13,
                            ContactNumber = "871-785-2891",
                            Title = "Chrysler"
                        },
                        new
                        {
                            Id = 83,
                            ContactDetailId = 36,
                            ContactNumber = "976-669-9091",
                            Title = "Saab"
                        },
                        new
                        {
                            Id = 84,
                            ContactDetailId = 23,
                            ContactNumber = "130-978-6875",
                            Title = "Cadillac"
                        },
                        new
                        {
                            Id = 85,
                            ContactDetailId = 45,
                            ContactNumber = "763-746-1557",
                            Title = "Mercedes-Benz"
                        },
                        new
                        {
                            Id = 86,
                            ContactDetailId = 23,
                            ContactNumber = "593-244-4192",
                            Title = "Acura"
                        },
                        new
                        {
                            Id = 87,
                            ContactDetailId = 26,
                            ContactNumber = "328-787-6694",
                            Title = "Volkswagen"
                        },
                        new
                        {
                            Id = 88,
                            ContactDetailId = 14,
                            ContactNumber = "300-945-2391",
                            Title = "Infiniti"
                        },
                        new
                        {
                            Id = 89,
                            ContactDetailId = 3,
                            ContactNumber = "479-423-7764",
                            Title = "Chevrolet"
                        },
                        new
                        {
                            Id = 90,
                            ContactDetailId = 18,
                            ContactNumber = "328-130-9937",
                            Title = "Toyota"
                        },
                        new
                        {
                            Id = 91,
                            ContactDetailId = 12,
                            ContactNumber = "295-163-6862",
                            Title = "Ford"
                        },
                        new
                        {
                            Id = 92,
                            ContactDetailId = 16,
                            ContactNumber = "537-207-7129",
                            Title = "Pontiac"
                        },
                        new
                        {
                            Id = 93,
                            ContactDetailId = 31,
                            ContactNumber = "548-657-4352",
                            Title = "Chevrolet"
                        },
                        new
                        {
                            Id = 94,
                            ContactDetailId = 12,
                            ContactNumber = "520-251-6769",
                            Title = "Mercedes-Benz"
                        },
                        new
                        {
                            Id = 95,
                            ContactDetailId = 26,
                            ContactNumber = "855-792-4948",
                            Title = "Volkswagen"
                        },
                        new
                        {
                            Id = 96,
                            ContactDetailId = 12,
                            ContactNumber = "332-682-2990",
                            Title = "Chevrolet"
                        },
                        new
                        {
                            Id = 97,
                            ContactDetailId = 50,
                            ContactNumber = "141-709-7411",
                            Title = "Chevrolet"
                        },
                        new
                        {
                            Id = 98,
                            ContactDetailId = 40,
                            ContactNumber = "136-266-6516",
                            Title = "Porsche"
                        },
                        new
                        {
                            Id = 99,
                            ContactDetailId = 30,
                            ContactNumber = "625-680-8992",
                            Title = "Mercedes-Benz"
                        },
                        new
                        {
                            Id = 100,
                            ContactDetailId = 2,
                            ContactNumber = "340-687-7098",
                            Title = "Volvo"
                        },
                        new
                        {
                            Id = 101,
                            ContactDetailId = 35,
                            ContactNumber = "314-801-1158",
                            Title = "Pontiac"
                        },
                        new
                        {
                            Id = 102,
                            ContactDetailId = 36,
                            ContactNumber = "830-570-8542",
                            Title = "Buick"
                        },
                        new
                        {
                            Id = 103,
                            ContactDetailId = 33,
                            ContactNumber = "253-582-3970",
                            Title = "Lexus"
                        },
                        new
                        {
                            Id = 104,
                            ContactDetailId = 31,
                            ContactNumber = "239-530-7488",
                            Title = "Cadillac"
                        },
                        new
                        {
                            Id = 105,
                            ContactDetailId = 22,
                            ContactNumber = "919-705-4021",
                            Title = "Acura"
                        },
                        new
                        {
                            Id = 106,
                            ContactDetailId = 27,
                            ContactNumber = "812-730-1567",
                            Title = "Honda"
                        },
                        new
                        {
                            Id = 107,
                            ContactDetailId = 32,
                            ContactNumber = "276-580-7772",
                            Title = "Morgan"
                        },
                        new
                        {
                            Id = 108,
                            ContactDetailId = 47,
                            ContactNumber = "456-535-5168",
                            Title = "Lexus"
                        },
                        new
                        {
                            Id = 109,
                            ContactDetailId = 42,
                            ContactNumber = "927-499-6495",
                            Title = "Land Rover"
                        },
                        new
                        {
                            Id = 110,
                            ContactDetailId = 18,
                            ContactNumber = "720-371-5333",
                            Title = "Nissan"
                        },
                        new
                        {
                            Id = 111,
                            ContactDetailId = 3,
                            ContactNumber = "319-558-2759",
                            Title = "Aston Martin"
                        },
                        new
                        {
                            Id = 112,
                            ContactDetailId = 31,
                            ContactNumber = "960-875-4009",
                            Title = "Mitsubishi"
                        },
                        new
                        {
                            Id = 113,
                            ContactDetailId = 23,
                            ContactNumber = "678-836-3442",
                            Title = "Nissan"
                        },
                        new
                        {
                            Id = 114,
                            ContactDetailId = 34,
                            ContactNumber = "191-164-9460",
                            Title = "Chevrolet"
                        },
                        new
                        {
                            Id = 115,
                            ContactDetailId = 12,
                            ContactNumber = "460-471-5226",
                            Title = "Ford"
                        },
                        new
                        {
                            Id = 116,
                            ContactDetailId = 34,
                            ContactNumber = "716-904-2654",
                            Title = "Suzuki"
                        },
                        new
                        {
                            Id = 117,
                            ContactDetailId = 46,
                            ContactNumber = "976-671-1081",
                            Title = "BMW"
                        },
                        new
                        {
                            Id = 118,
                            ContactDetailId = 35,
                            ContactNumber = "294-841-4639",
                            Title = "Honda"
                        },
                        new
                        {
                            Id = 119,
                            ContactDetailId = 1,
                            ContactNumber = "516-242-9457",
                            Title = "GMC"
                        },
                        new
                        {
                            Id = 120,
                            ContactDetailId = 46,
                            ContactNumber = "537-258-4554",
                            Title = "Saab"
                        },
                        new
                        {
                            Id = 121,
                            ContactDetailId = 1,
                            ContactNumber = "197-664-0956",
                            Title = "Audi"
                        },
                        new
                        {
                            Id = 122,
                            ContactDetailId = 45,
                            ContactNumber = "147-391-1583",
                            Title = "Mercedes-Benz"
                        },
                        new
                        {
                            Id = 123,
                            ContactDetailId = 25,
                            ContactNumber = "482-135-5504",
                            Title = "Acura"
                        },
                        new
                        {
                            Id = 124,
                            ContactDetailId = 13,
                            ContactNumber = "439-940-7805",
                            Title = "Toyota"
                        },
                        new
                        {
                            Id = 125,
                            ContactDetailId = 34,
                            ContactNumber = "532-324-7186",
                            Title = "BMW"
                        },
                        new
                        {
                            Id = 126,
                            ContactDetailId = 9,
                            ContactNumber = "208-994-1505",
                            Title = "Kia"
                        },
                        new
                        {
                            Id = 127,
                            ContactDetailId = 44,
                            ContactNumber = "373-986-4768",
                            Title = "Porsche"
                        },
                        new
                        {
                            Id = 128,
                            ContactDetailId = 44,
                            ContactNumber = "594-444-2967",
                            Title = "Mercedes-Benz"
                        },
                        new
                        {
                            Id = 129,
                            ContactDetailId = 10,
                            ContactNumber = "907-916-3956",
                            Title = "Mercedes-Benz"
                        },
                        new
                        {
                            Id = 130,
                            ContactDetailId = 35,
                            ContactNumber = "296-381-9769",
                            Title = "Pontiac"
                        },
                        new
                        {
                            Id = 131,
                            ContactDetailId = 47,
                            ContactNumber = "151-215-4523",
                            Title = "Audi"
                        },
                        new
                        {
                            Id = 132,
                            ContactDetailId = 31,
                            ContactNumber = "532-539-8198",
                            Title = "Mitsubishi"
                        },
                        new
                        {
                            Id = 133,
                            ContactDetailId = 34,
                            ContactNumber = "231-324-4233",
                            Title = "Pontiac"
                        },
                        new
                        {
                            Id = 134,
                            ContactDetailId = 6,
                            ContactNumber = "224-740-9436",
                            Title = "Hillman"
                        },
                        new
                        {
                            Id = 135,
                            ContactDetailId = 4,
                            ContactNumber = "691-868-5507",
                            Title = "Ford"
                        },
                        new
                        {
                            Id = 136,
                            ContactDetailId = 49,
                            ContactNumber = "987-544-1076",
                            Title = "BMW"
                        },
                        new
                        {
                            Id = 137,
                            ContactDetailId = 38,
                            ContactNumber = "298-785-5863",
                            Title = "Hyundai"
                        },
                        new
                        {
                            Id = 138,
                            ContactDetailId = 46,
                            ContactNumber = "766-927-6857",
                            Title = "Lincoln"
                        },
                        new
                        {
                            Id = 139,
                            ContactDetailId = 43,
                            ContactNumber = "404-167-0926",
                            Title = "Oldsmobile"
                        },
                        new
                        {
                            Id = 140,
                            ContactDetailId = 6,
                            ContactNumber = "770-827-0153",
                            Title = "Infiniti"
                        },
                        new
                        {
                            Id = 141,
                            ContactDetailId = 29,
                            ContactNumber = "263-994-0271",
                            Title = "Mercury"
                        },
                        new
                        {
                            Id = 142,
                            ContactDetailId = 45,
                            ContactNumber = "620-185-9930",
                            Title = "Buick"
                        },
                        new
                        {
                            Id = 143,
                            ContactDetailId = 29,
                            ContactNumber = "310-305-3616",
                            Title = "Chrysler"
                        },
                        new
                        {
                            Id = 144,
                            ContactDetailId = 33,
                            ContactNumber = "433-983-4858",
                            Title = "GMC"
                        },
                        new
                        {
                            Id = 145,
                            ContactDetailId = 25,
                            ContactNumber = "509-949-0724",
                            Title = "Volkswagen"
                        },
                        new
                        {
                            Id = 146,
                            ContactDetailId = 34,
                            ContactNumber = "395-290-0542",
                            Title = "Mercedes-Benz"
                        },
                        new
                        {
                            Id = 147,
                            ContactDetailId = 23,
                            ContactNumber = "428-347-0136",
                            Title = "Ford"
                        },
                        new
                        {
                            Id = 148,
                            ContactDetailId = 6,
                            ContactNumber = "211-546-6585",
                            Title = "Subaru"
                        },
                        new
                        {
                            Id = 149,
                            ContactDetailId = 3,
                            ContactNumber = "654-369-6742",
                            Title = "Toyota"
                        },
                        new
                        {
                            Id = 150,
                            ContactDetailId = 1,
                            ContactNumber = "527-346-1864",
                            Title = "Lexus"
                        },
                        new
                        {
                            Id = 151,
                            ContactDetailId = 16,
                            ContactNumber = "181-661-7391",
                            Title = "Cadillac"
                        },
                        new
                        {
                            Id = 152,
                            ContactDetailId = 4,
                            ContactNumber = "612-446-6785",
                            Title = "Lincoln"
                        },
                        new
                        {
                            Id = 153,
                            ContactDetailId = 38,
                            ContactNumber = "977-523-5909",
                            Title = "Honda"
                        },
                        new
                        {
                            Id = 154,
                            ContactDetailId = 30,
                            ContactNumber = "125-675-5360",
                            Title = "GMC"
                        },
                        new
                        {
                            Id = 155,
                            ContactDetailId = 31,
                            ContactNumber = "129-736-5272",
                            Title = "Daewoo"
                        },
                        new
                        {
                            Id = 156,
                            ContactDetailId = 39,
                            ContactNumber = "574-559-2339",
                            Title = "Ford"
                        },
                        new
                        {
                            Id = 157,
                            ContactDetailId = 32,
                            ContactNumber = "677-565-6890",
                            Title = "Acura"
                        },
                        new
                        {
                            Id = 158,
                            ContactDetailId = 34,
                            ContactNumber = "379-655-8365",
                            Title = "Hyundai"
                        },
                        new
                        {
                            Id = 159,
                            ContactDetailId = 16,
                            ContactNumber = "237-837-2120",
                            Title = "Chevrolet"
                        },
                        new
                        {
                            Id = 160,
                            ContactDetailId = 24,
                            ContactNumber = "528-523-7443",
                            Title = "Alfa Romeo"
                        },
                        new
                        {
                            Id = 161,
                            ContactDetailId = 19,
                            ContactNumber = "922-751-9424",
                            Title = "Volkswagen"
                        },
                        new
                        {
                            Id = 162,
                            ContactDetailId = 22,
                            ContactNumber = "702-801-3973",
                            Title = "Volvo"
                        },
                        new
                        {
                            Id = 163,
                            ContactDetailId = 43,
                            ContactNumber = "884-401-2793",
                            Title = "Ford"
                        },
                        new
                        {
                            Id = 164,
                            ContactDetailId = 27,
                            ContactNumber = "554-259-4204",
                            Title = "GMC"
                        },
                        new
                        {
                            Id = 165,
                            ContactDetailId = 2,
                            ContactNumber = "689-846-8929",
                            Title = "Hyundai"
                        },
                        new
                        {
                            Id = 166,
                            ContactDetailId = 1,
                            ContactNumber = "226-506-0668",
                            Title = "BMW"
                        },
                        new
                        {
                            Id = 167,
                            ContactDetailId = 34,
                            ContactNumber = "789-476-6014",
                            Title = "Audi"
                        },
                        new
                        {
                            Id = 168,
                            ContactDetailId = 38,
                            ContactNumber = "800-557-6114",
                            Title = "BMW"
                        },
                        new
                        {
                            Id = 169,
                            ContactDetailId = 36,
                            ContactNumber = "159-792-2219",
                            Title = "Mercedes-Benz"
                        },
                        new
                        {
                            Id = 170,
                            ContactDetailId = 25,
                            ContactNumber = "801-700-0002",
                            Title = "Mercury"
                        },
                        new
                        {
                            Id = 171,
                            ContactDetailId = 16,
                            ContactNumber = "407-173-2383",
                            Title = "GMC"
                        },
                        new
                        {
                            Id = 172,
                            ContactDetailId = 36,
                            ContactNumber = "827-395-5702",
                            Title = "Ford"
                        },
                        new
                        {
                            Id = 173,
                            ContactDetailId = 44,
                            ContactNumber = "951-986-9157",
                            Title = "Ford"
                        },
                        new
                        {
                            Id = 174,
                            ContactDetailId = 45,
                            ContactNumber = "202-422-6406",
                            Title = "Audi"
                        },
                        new
                        {
                            Id = 175,
                            ContactDetailId = 36,
                            ContactNumber = "239-104-1608",
                            Title = "Dodge"
                        },
                        new
                        {
                            Id = 176,
                            ContactDetailId = 17,
                            ContactNumber = "602-528-0641",
                            Title = "Chevrolet"
                        },
                        new
                        {
                            Id = 177,
                            ContactDetailId = 17,
                            ContactNumber = "568-375-8204",
                            Title = "Suzuki"
                        },
                        new
                        {
                            Id = 178,
                            ContactDetailId = 21,
                            ContactNumber = "489-213-2781",
                            Title = "Mazda"
                        },
                        new
                        {
                            Id = 179,
                            ContactDetailId = 1,
                            ContactNumber = "848-287-3230",
                            Title = "Suzuki"
                        },
                        new
                        {
                            Id = 180,
                            ContactDetailId = 35,
                            ContactNumber = "445-625-2093",
                            Title = "Ford"
                        },
                        new
                        {
                            Id = 181,
                            ContactDetailId = 24,
                            ContactNumber = "901-306-4372",
                            Title = "Chevrolet"
                        },
                        new
                        {
                            Id = 182,
                            ContactDetailId = 24,
                            ContactNumber = "176-697-1898",
                            Title = "Ford"
                        },
                        new
                        {
                            Id = 183,
                            ContactDetailId = 14,
                            ContactNumber = "618-286-0745",
                            Title = "Acura"
                        },
                        new
                        {
                            Id = 184,
                            ContactDetailId = 46,
                            ContactNumber = "180-335-1507",
                            Title = "Mercedes-Benz"
                        },
                        new
                        {
                            Id = 185,
                            ContactDetailId = 34,
                            ContactNumber = "612-189-1954",
                            Title = "Nissan"
                        },
                        new
                        {
                            Id = 186,
                            ContactDetailId = 4,
                            ContactNumber = "520-746-5147",
                            Title = "Nissan"
                        },
                        new
                        {
                            Id = 187,
                            ContactDetailId = 41,
                            ContactNumber = "664-291-4141",
                            Title = "GMC"
                        },
                        new
                        {
                            Id = 188,
                            ContactDetailId = 39,
                            ContactNumber = "643-635-8231",
                            Title = "Toyota"
                        },
                        new
                        {
                            Id = 189,
                            ContactDetailId = 46,
                            ContactNumber = "376-117-1426",
                            Title = "Mazda"
                        },
                        new
                        {
                            Id = 190,
                            ContactDetailId = 4,
                            ContactNumber = "350-661-5646",
                            Title = "Mitsubishi"
                        },
                        new
                        {
                            Id = 191,
                            ContactDetailId = 40,
                            ContactNumber = "457-572-2190",
                            Title = "Toyota"
                        },
                        new
                        {
                            Id = 192,
                            ContactDetailId = 17,
                            ContactNumber = "877-945-0372",
                            Title = "Mercury"
                        },
                        new
                        {
                            Id = 193,
                            ContactDetailId = 3,
                            ContactNumber = "641-827-1470",
                            Title = "Subaru"
                        },
                        new
                        {
                            Id = 194,
                            ContactDetailId = 34,
                            ContactNumber = "427-513-1901",
                            Title = "Acura"
                        },
                        new
                        {
                            Id = 195,
                            ContactDetailId = 35,
                            ContactNumber = "729-532-7107",
                            Title = "Suzuki"
                        },
                        new
                        {
                            Id = 196,
                            ContactDetailId = 35,
                            ContactNumber = "429-759-0361",
                            Title = "Buick"
                        },
                        new
                        {
                            Id = 197,
                            ContactDetailId = 50,
                            ContactNumber = "206-895-4678",
                            Title = "Land Rover"
                        },
                        new
                        {
                            Id = 198,
                            ContactDetailId = 13,
                            ContactNumber = "445-719-1398",
                            Title = "Saab"
                        },
                        new
                        {
                            Id = 199,
                            ContactDetailId = 5,
                            ContactNumber = "580-613-8368",
                            Title = "Lexus"
                        },
                        new
                        {
                            Id = 200,
                            ContactDetailId = 16,
                            ContactNumber = "809-279-7941",
                            Title = "Toyota"
                        });
                });

            modelBuilder.Entity("MyContacts.DataAccessLayer.ContactInformation.ContactDetail", b =>
                {
                    b.HasOne("MyContacts.DataAccessLayer.ContactInformation.Label", "Label")
                        .WithMany()
                        .HasForeignKey("LabelId");

                    b.Navigation("Label");
                });

            modelBuilder.Entity("MyContacts.DataAccessLayer.ContactInformation.PhoneNumber", b =>
                {
                    b.HasOne("MyContacts.DataAccessLayer.ContactInformation.ContactDetail", "ContactDetail")
                        .WithMany("PhoneNumbers")
                        .HasForeignKey("ContactDetailId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("ContactDetail");
                });

            modelBuilder.Entity("MyContacts.DataAccessLayer.ContactInformation.ContactDetail", b =>
                {
                    b.Navigation("PhoneNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
